name: study_hub
description: "A student productivity app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # For local SQL database storage
  sqflite: ^2.3.3

  # Helper package for sqflite to find the database path
  path: ^1.9.0

  # To generate unique IDs for notes and deadlines
  uuid: ^4.4.0

  # For formatting dates and times
  intl: ^0.19.0

  # Firebase for Class Whisper and Notes Sharing
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5

  # Local notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  # Sharing and file operations
  share_plus: ^7.2.2
  file_picker: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

  # CSV export for ClassSplit
  csv: ^6.0.0

  # QR code for sharing
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

  # Bluetooth and nearby sharing
  nearby_connections: ^4.3.0

  # PDF viewer and creation
  flutter_pdfview: ^1.3.2
  pdf: ^3.10.8
  url_launcher: ^6.3.1

  # Charts for analytics and grade tracking
  fl_chart: ^0.66.2

  # For study timer and stopwatch
  stop_watch_timer: ^3.1.1

  # Better UI components
  flutter_slidable: ^3.1.0
  animations: ^2.0.11

  # Standard iOS style icons
  cupertino_icons: ^1.0.2

  # Shared preferences for settings
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true