name: spotify_clone
description: A Spotify clone built in Flutter.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  just_audio: ^0.9.41
  audio_session: ^0.1.7
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
