name: persistent_notes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3 # Use this instead of path_provider
  cupertino_icons: ^1.0.2
  firebase_core: ^2.30.0 # Should be added by CLI
  cloud_firestore: ^4.17.0 # Add this line
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true